### ISSUE TITLE
LangGraph docker compose 100% CPU usage

### ISSUE THREAD

**Issue by TimurMunykin** [langchain-ai/langgraph#3366]
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [x] I added a clear and detailed title that summarizes the issue.
- [x] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [x] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
# LangGraph Docker 100 CPU Issue
Based on manuals:
- https://langchain-ai.github.io/langgraph/how-tos/deploy-self-hosted/#using-docker
- https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-1-build-a-basic-chatbot

What I did:

python3.11 -m venv .venv


source .venv/bin/activate


python3 --version
Python 3.11.11


pip install -U langgraph-cli


langgraph build -t my-image


docker compose up -d
```

### Error Message and Stack Trace (if applicable)

```shell
#log from container
Executing task: docker logs --tail 1000 -f 17d8796d5938042773496dd98afee1314da7a2a5e0b477f813b68f12bf46fb1d 

2025-02-09T19:36:33.445133Z [info     ] Using auth of type=noop        [langgraph_api.auth.middleware] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.452650Z [info     ] Started server process [1]     [uvicorn.error] api_revision=7d5eecb api_variant=local color_message='Started server process [\x1b[36m%d\x1b[0m]'
2025-02-09T19:36:33.452835Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.453088Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.873404Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.927013Z [info     ] No LANGGRAPH_STORE configuration found, using default configuration [langgraph_storage.database] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.929783Z [info     ] Postgres pool stats            [langgraph_storage.database] api_revision=7d5eecb api_variant=local connections_ms=13 connections_num=1 pool_available=1 pool_max=150 pool_min=1 pool_size=1 requests_num=1 requests_waiting=0 usage_ms=1
2025-02-09T19:36:33.932606Z [info     ] Redis pool stats               [langgraph_storage.redis] api_revision=7d5eecb api_variant=local idle_connections=1 in_use_connections=0 max_connections=500
2025-02-09T19:36:33.942666Z [info     ] Registering graph with id 'my_agent' [langgraph_api.graph] api_revision=7d5eecb api_variant=local graph_id=my_agent
2025-02-09T19:36:33.946778Z [info     ] Starting metadata loop         [langgraph_api.metadata] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.947942Z [info     ] Application startup complete.  [uvicorn.error] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.948665Z [info     ] Starting 10 background workers [langgraph_api.queue] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:33.949463Z [info     ] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit) [uvicorn.error] api_revision=7d5eecb api_variant=local color_message='Uvicorn running on \x1b[1m%s://%s:%d\x1b[0m (Press CTRL+C to quit)'
2025-02-09T19:36:33.950474Z [info     ] Worker stats                   [langgraph_api.queue] active=0 api_revision=7d5eecb api_variant=local available=10 max=10
2025-02-09T19:36:33.955662Z [info     ] Queue stats                    [langgraph_api.queue] api_revision=7d5eecb api_variant=local med_age_secs=None min_age_secs=None n_pending=0 n_running=0
2025-02-09T19:36:33.982250Z [info     ] Sweeped runs                   [langgraph_api.queue] api_revision=7d5eecb api_variant=local run_ids=[]
2025-02-09T19:36:34.121100Z [info     ] HTTP Request: POST https://api.smith.langchain.com/v1/metadata/submit "HTTP/1.1 204 No Content" [httpx] api_revision=7d5eecb api_variant=local
2025-02-09T19:36:36.935696Z [info     ] GET /ok 200 0ms                [langgraph_api.server] api_revision=7d5eecb api_variant=local latency_ms=0 method=GET path=/ok path_params={} proto=1.1 query_string= req_header={'accept-encoding': 'identity', 'host': 'localhost:8000', 'user-agent': 'Python-urllib/3.11', 'connection': 'close'} res_header={'content-length': '11', 'content-type': 'application/json'} route=None status=200
2025-02-09T19:36:42.057932Z [info     ] GET /ok 200 0ms                [langgraph_api.server] api_revision=7d5eecb api_variant=local latency_ms=0 method=GET path=/ok path_params={} proto=1.1 query_string= req_header={'accept-encoding': 'identity', 'host': 'localhost:8000', 'user-agent': 'Python-urllib/3.11', 'connection': 'close'} res_header={'content-length': '11', 'content-type': 'application/json'} route=None status=200
2025-02-09T19:36:47.202318Z [info     ] GET /ok 200 0ms                [langgraph_api.server] api_revision=7d5eecb api_variant=local latency_ms=0 method=GET path=/ok path_params={} proto=1.1 query_string= req_header={'accept-encoding': 'identity', 'host': 'localhost:8000', 'user-agent': 'Python-urllib/3.11', 'connection': 'close'} res_header={'content-length': '11', 'content-type': 'application/json'} route=None status=200
2025-02-09T19:36:52.351129Z [info     ] GET /ok 200 0ms                [langgraph_api.server] api_revision=7d5eecb api_variant=local latency_ms=0 method=GET path=/ok path_params={} proto=1.1 query_string= req_header={'accept-encoding': 'identity', 'host': 'localhost:8000', 'user-agent': 'Python-urllib/3.11', 'connection': 'close'} res_header={'content-length': '11', 'content-type': 'application/json'} route=None status=200
2025-02-09T19:36:57.504541Z [info     ] GET /ok 200 0ms                [langgraph_api.server] api_revision=7d5eecb api_variant=local latency_ms=0 method=GET path=/ok path_params={} proto=1.1 query_string= req_header={'accept-encoding': 'identity', 'host': 'localhost:8000', 'user-agent': 'Python-urllib/3.11', 'connection': 'close'} res_header={'content-length': '11', 'content-type': 'application/json'} route=None status=200
```

### Description

I have an issue with 100% CPU running self-hosted Langgraph with docker-compose.
Here is an example that you can easily run https://github.com/TimurMunykin/langgraph_issue

### System Info

root@17d8796d5938:/deps/__outer_langgraph_issue/src# python -m langchain_core.sys_info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Mon Dec  4 10:03:25 UTC 2023
> Python Version:  3.11.11 (main, Feb  4 2025, 04:55:09) [GCC 12.2.0]

Package Information
-------------------
> langchain_core: 0.3.34
> langsmith: 0.3.7
> langgraph_api: 0.0.22
> langgraph_license: Installed. No version info available.
> langgraph_sdk: 0.1.51
> langgraph_storage: Installed. No version info available.

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> cryptography: 44.0.0
> httpx: 0.28.1
> jsonpatch<2.0,>=1.33: Installed. No version info available.
> jsonschema-rs: 0.29.1
> langgraph: 0.2.70
> langgraph-checkpoint: 2.0.10
> langsmith-pyo3: Installed. No version info available.
> langsmith<0.4,>=0.1.125: Installed. No version info available.
> orjson: 3.10.15
> packaging<25,>=23.2: Installed. No version info available.
> pydantic: 2.10.6
> pydantic<3.0.0,>=2.5.2;: Installed. No version info available.
> pydantic<3.0.0,>=2.7.4;: Installed. No version info available.
> pyjwt: 2.10.1
> pytest: Installed. No version info available.
> PyYAML>=5.3: Installed. No version info available.
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> rich: Installed. No version info available.
> sse-starlette: 2.1.3
> starlette: 0.45.3
> structlog: 25.1.0
> tenacity: 9.0.0
> tenacity!=8.4.0,<10.0.0,>=8.1.0: Installed. No version info available.
> typing-extensions>=4.7: Installed. No version info available.
> uvicorn: 0.34.0
> watchfiles: Installed. No version info available.
> zstandard: 0.23.0

**Comment by lironezra** [comment]
Hi, 
We also experienced this issue with 100% CPU.

**Comment by codebreach** [comment]
we are also experiencing this issue - and there isnt any documentation on it

**Comment by TimurMunykin** [comment]
@lironezra @codebreach
As a temporary solution, you could limit CPU resources directly in your Docker Compose configuration. For example:

```yaml
deploy:
  resources:
    limits:
      cpus: "0.7"
```

**Comment by Michailbul** [comment]
we actually faced the issue with the postgres container as well

**Comment by hinthornw** [comment]
Which docker image sha are you seeing this on? 

While CPU usage didn't actually impact runtime perf, older versions showed high usage while polling for new runs. We fixed how the queue works which should drop this.

**Comment by hinthornw** [comment]
Feel free to re-open this thread, but I believe based on confirmations from other people reporting this that this is fixed in more recent base images.

**Comment by TimurMunykin** [comment]
Thanks, sorry for not responding for a long time. Now it's fixed and does not load the CPU to 100%

**Comment by tsvidya** [comment]
Updated the version to 0.3.8. I still have the same issue of hitting 100% CPU. This is with respect to the usual deployment not the docker image. Any help is appreciated.
